### ISSUE TITLE
question about log info

### ISSUE THREAD

**Issue by WackenChan** [PacktPublishing/Learning-Spring-5.0#1]
I'd like to ask how to configure my spring to let it print the log info on the console just like it's shown in the book (page 25, color red log output). I am using spring 5.3.2. Thanks for your consideration.

**Comment by deepesh-packt** [comment]
1. add log4j-x.y.z.jar in the project as a dependency
2. add log messages in the .java files
3. add log4j.properties file in classpath which will set loggers and where to display the messages etc.
